hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"

[[files]]
file = "filesToRemove.txt"

[[files]]
file = "mods/iris-flw-compat.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true
