name = "GamersMarinaded"
author = "Gamers"
version = "v1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c5aa06974959250809568feef1b8c6481a53d38fd1ace21875ea48fae95e36a"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
