name = "GamersMarinaded"
author = "Gamers"
version = "v1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecc9a42b8ff4f27720fde86e500d7b3259f37163f5b054da51ccd99b42b252e4"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
