name = "GamersMarinaded 2"
author = "Gamers"
version = "v3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f86af07033eb41ef4a243922717e0b7a94554f34c85012e10c70aaf6a06a31e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
