name = "GamersMarinaded"
author = "Gamers"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6282ee61fab11752652b2bccbf4b0a89c57d655a6f6ec6c11ee8ce7f09e01d8"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
