name = "GamersMarinaded"
author = "Gamers"
version = "v14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c46360bc51bb06c9d62835b49f6fab1832ef76af7f7d8d6ee0d66b2ded1f0d09"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
