name = "GamersMarinaded"
author = "Gamers"
version = "v1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69cb47da0cc4db702ca0ccd1674c976fbecd67435ad67685cb1e7899ccd05289"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
