name = "GamersMarinaded 2"
author = "Gamers"
version = "v3b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a298bff516c4f4feeb6d75e6473d9bcb0d50582db3414add9cb481af71fb5a36"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
