name = "GamersMarinaded"
author = "Gamers"
version = "v6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "921aee9c2ae352a44d8cd877e5cb8fbf8311954295a05346a15b720c17e0ad3e"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
