name = "GamersMarinaded 2"
author = "Gamers"
version = "v3b3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7fe5a2de6e5841a5b88ef9fde485775f342fc998bbd2e42f7400db92f80f3e6"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
