name = "GamersMarinaded"
author = "Gamers"
version = "v10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8290cf47d0ab49cef6d20d552e8190d357f6b6a9157eb5aa669762f44d7ac9b"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
