name = "GamersMarinaded"
author = "Gamers"
version = "v9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "111f7617f883d30aa37291e002aa499e9c2f667abf8b7813b1df4c6edf3f6623"

[versions]
forge = "47.3.27"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
