name = "GamersMarinaded 2"
author = "Gamers"
version = "v1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e08350913dcbc878bee392c63301f2a19c6bf0e66c4e237896e22812a833ad94"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
