name = "GamersMarinaded"
author = "Gamers"
version = "v5.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed72311270134a877448b1d688370f0e4a33d731dfbb86d2d21caba10ecafef4"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
