name = "GamersMarinaded 2"
author = "Gamers"
version = "2-v1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38ca85d0a117693557942fd4d933feab1bcb6b5731f5487e47ff9f2f1504b463"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
