name = "GamersMarinaded"
author = "Gamers"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b961341fccfac6e3cca9e911ada0dcc9eb5e04c92d073ecfdc35c9f5f07fa305"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
