hash-format = "sha256"

[[files]]
file = "config/bcc-common.toml"

[[files]]
file = "config/does_it_tick-common.toml"

[[files]]
file = "config/openloader/advanced_options.json"

[[files]]
file = "config/openloader/data/interloper.pw.toml"
metafile = true

[[files]]
file = "config/quark-common.toml"

[[files]]
file = "config/vampirism-common.toml"

[[files]]
file = "mods/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/ancient-golems.pw.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/aquaculture.pw.toml"
metafile = true

[[files]]
file = "mods/aquamirae.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/ars-elemental.pw.toml"
metafile = true

[[files]]
file = "mods/ars-energistique.pw.toml"
metafile = true

[[files]]
file = "mods/ars-nouveau-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
metafile = true

[[files]]
file = "mods/astemirlib.pw.toml"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
metafile = true

[[files]]
file = "mods/choicetheorems-overhauled-village.pw.toml"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/corail-tombstone.pw.toml"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
metafile = true

[[files]]
file = "mods/create-applied-kinetics.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
metafile = true

[[files]]
file = "mods/croptopia-delight.pw.toml"
metafile = true

[[files]]
file = "mods/croptopia.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-create-structures.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-farmers-delight-compat.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
metafile = true

[[files]]
file = "mods/enigmatic-legacy.pw.toml"
metafile = true

[[files]]
file = "mods/epherolib.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/formations.pw.toml"
metafile = true

[[files]]
file = "mods/framedblocks.pw.toml"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
metafile = true

[[files]]
file = "mods/goblin-traders.pw.toml"
metafile = true

[[files]]
file = "mods/guide-api.pw.toml"
metafile = true

[[files]]
file = "mods/iam-music-player.pw.toml"
metafile = true

[[files]]
file = "mods/ice-and-fire-dragons.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
metafile = true

[[files]]
file = "mods/item-production-lib.pw.toml"
metafile = true

[[files]]
file = "mods/iter-rpg.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/joy-of-painting.pw.toml"
metafile = true

[[files]]
file = "mods/json-things.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/lendercataclysm.pw.toml"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/mana-and-artifice.pw.toml"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
metafile = true

[[files]]
file = "mods/medieval-buildings.pw.toml"
metafile = true

[[files]]
file = "mods/medieval-origins-revival.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-additions.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/more-player-models.pw.toml"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/mystics-biomes.pw.toml"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/origins-forge.pw.toml"
metafile = true

[[files]]
file = "mods/origins-kitsune.pw.toml"
metafile = true

[[files]]
file = "mods/otyacraft-engine.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/philips-ruins.pw.toml"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
metafile = true

[[files]]
file = "mods/pneumaticcraft-repressurized.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/polymorphic-energistics.pw.toml"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
metafile = true

[[files]]
file = "mods/rats.pw.toml"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/relics-mod.pw.toml"
metafile = true

[[files]]
file = "mods/shineals-prehistoric-expansion.pw.toml"
metafile = true

[[files]]
file = "mods/simple-login.pw.toml"
metafile = true

[[files]]
file = "mods/smartbrainlib.pw.toml"
metafile = true

[[files]]
file = "mods/spartan-shields.pw.toml"
metafile = true

[[files]]
file = "mods/spartan-weaponry.pw.toml"
metafile = true

[[files]]
file = "mods/stellarity.pw.toml"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/the-graveyard-forge.pw.toml"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
metafile = true

[[files]]
file = "mods/tinkers-katanas.pw.toml"
metafile = true

[[files]]
file = "mods/tinkers-levelling-addon.pw.toml"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
metafile = true

[[files]]
file = "mods/travelers-backpack.pw.toml"
metafile = true

[[files]]
file = "mods/unnamed-desert.pw.toml"
metafile = true

[[files]]
file = "mods/vampirism-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/vampirism.pw.toml"
metafile = true

[[files]]
file = "mods/villagersplus.pw.toml"
metafile = true

[[files]]
file = "mods/when-dungeons-arise-seven-seas.pw.toml"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
metafile = true
