name = "GamersMarinaded"
author = "Gamers"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ea5f328ab99921ff03bfe31c556b0182e4dcf6af4f8c74ae63cfa79ac9a2e10"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
