name = "GamersMarinaded"
author = "Gamers"
version = "v1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7649133f1f363af16d1ba3987b346177666f3086670bd7e83d5f3f0e376b7e80"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
