name = "GamersMarinaded"
author = "Gamers"
version = "v10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bf27b12c796924248e3e85d7c93d56bbddcbdeb37053f5341f76e08fc4854f5"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
