name = "GamersMarinaded 2"
author = "Gamers"
version = "v1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "123dffd05ae69ba5ce48c5d5060b9ec5d3970cbda4f8ebfcf00a231f06ae4872"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
