name = "GamersMarinaded"
author = "Gamers"
version = "v1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01f034ffc647f2817fd434a8053b0aaed29e284825b6331c0a2e06a8641ce748"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
no-internal-hashes = "true"
