hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"

[[files]]
file = "config/alexscaves-client.toml"

[[files]]
file = "config/create-client.toml"

[[files]]
file = "config/embeddium++.toml"

[[files]]
file = "config/fancymenu/assets/background.jpg"

[[files]]
file = "config/fancymenu/assets/icon16.png"

[[files]]
file = "config/fancymenu/assets/icon32.png"

[[files]]
file = "config/fancymenu/assets/logo.png"

[[files]]
file = "config/fancymenu/customizablemenus.txt"

[[files]]
file = "config/fancymenu/customization/main_menu.txt"

[[files]]
file = "config/fancymenu/options.txt"

[[files]]
file = "config/iceandfire-client.toml"

[[files]]
file = "config/openloader/resources/ModPack Resources/assets/multiverse/lang/ru_ru.json"

[[files]]
file = "config/openloader/resources/ModPack Resources/assets/multiverse/lang/uk_ua.json"

[[files]]
file = "config/openloader/resources/ModPack Resources/assets/simplelogin/lang/en_us.json"

[[files]]
file = "config/openloader/resources/ModPack Resources/assets/simplelogin/lang/ru_ru.json"

[[files]]
file = "config/openloader/resources/ModPack Resources/assets/simplelogin/lang/uk_ua.json"

[[files]]
file = "config/quark-common.toml"

[[files]]
file = "config/supplementaries-client.toml"

[[files]]
file = "config/xaerominimap.txt"

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
metafile = true

[[files]]
file = "mods/tconjei.pw.toml"
metafile = true
